# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 29) do

  create_table "comparacion_sueldos", :force => true do |t|
    t.column "salario_bruto_actual", :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "salario_bruto_futuro", :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "ticket_actual",        :decimal, :precision => 6,  :scale => 2, :default => 0.0
    t.column "ticket_futuro",        :decimal, :precision => 6,  :scale => 2, :default => 0.0
    t.column "bonus_actual",         :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "bonus_futuro",         :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "cantidad_hijos",       :integer,                                :default => 0
    t.column "otras_cargas",         :integer,                                :default => 0
    t.column "deduce_conyuge",       :boolean,                                :default => false
  end

  create_table "info_news", :force => true do |t|
    t.column "titulo",      :string
    t.column "descripcion", :string
    t.column "url_noticia", :string
    t.column "categoria",   :string
    t.column "fecha",       :date
    t.column "mostrar",     :boolean
  end

  add_index "info_news", ["fecha"], :name => "index_info_news_on_fecha"

  create_table "monthly_salaries", :force => true do |t|
    t.column "month",        :string
    t.column "gross_salary", :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "ticket",       :decimal, :precision => 6,  :scale => 2, :default => 0.0
    t.column "bonus",        :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "salary_id",    :integer,                                                 :null => false
  end

  create_table "positions", :force => true do |t|
    t.column "name",        :string
    t.column "description", :string
  end

  create_table "reduction_taxes", :force => true do |t|
    t.column "month",                :string
    t.column "from_salary",          :decimal, :precision => 12, :scale => 2, :default => 0.0
    t.column "to_salary",            :decimal, :precision => 12, :scale => 2, :default => 0.0
    t.column "reduction_percentage", :decimal, :precision => 8,  :scale => 2, :default => 0.0
  end

  create_table "revenue_parameter_details", :force => true do |t|
    t.column "month",                :string
    t.column "value",                :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "revenue_parameter_id", :integer,                                                 :null => false
  end

  create_table "revenue_parameters", :force => true do |t|
    t.column "year",       :integer
    t.column "name",       :string
    t.column "value",      :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "has_detail", :boolean,                                :default => false
  end

  create_table "revenue_taxes", :force => true do |t|
    t.column "month",       :string
    t.column "from_salary", :decimal, :precision => 12, :scale => 2, :default => 0.0
    t.column "to_salary",   :decimal, :precision => 12, :scale => 2, :default => 0.0
    t.column "tax_amount",  :decimal, :precision => 12, :scale => 2, :default => 0.0
    t.column "tax_rate",    :decimal, :precision => 8,  :scale => 2, :default => 0.0
  end

  create_table "salaries", :force => true do |t|
    t.column "position_id",    :integer,                    :null => false
    t.column "cantidad_hijos", :integer, :default => 0
    t.column "otras_cargas",   :integer, :default => 0
    t.column "deduce_conyuge", :boolean, :default => false
    t.column "anio_fiscal",    :integer, :default => 2008
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "special_discounts", :force => true do |t|
    t.column "month",                    :string
    t.column "seguro_retiro",            :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "seguro_vida",              :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "cuota_medica",             :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "donacion",                 :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "honorario_medico",         :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "intereses_hipotecarios",   :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "personal_domestico",       :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "aportes_voluntarios_afjp", :decimal, :precision => 10, :scale => 2, :default => 0.0
    t.column "salary_id",                :integer,                                                 :null => false
  end

end
